### ISSUE TITLE
PHP Fatal error after AliceBundle installation

### ISSUE THREAD

**Issue by kacperix** [hautelook/AliceBundle#214]
After I've installed AliceBundle Symfony throws an exception:

```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 2 passed to HautelookAliceBundleDoctrineCommandLoadDataFixturesCommand_0000000025f3c2290000000073837c9e0de979db516cb6266516079ba9efc4da::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, none given, called in /Users/przemek/Development/esnabel/var/cache/dev/appDevDebugProjectContainer.php on line 1490 in /Users/przemek/Development/esnabel/var/cache/dev/appDevDebugProjectContainer.php:5701
Stack trace:
#0 /Users/przemek/Development/esnabel/var/cache/dev/appDevDebugProjectContainer.php(1490): HautelookAliceBundleDoctrineCommandLoadDataFixturesCommand_0000000025f3c2290000000073837c9e0de979db516cb6266516079ba9efc4da->__construct(Object(Closure))
#1 /Users/przemek/Development/esnabel/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(273): appDevDebugProjectContainer->getHautelookAlice_Doctrine_Command_DeprecatedLoadCommandService()
#2 /Users/przemek/Development/esnabel/v in /Users/przemek/Development/esnabel/var/cache/dev/appDevDebugProjectContainer.php on line 5701
```

My Env:
* php 7 + OPCache
* symfony 3.0.0
* doctrine and fixtures bundles installed

Bundle installation command:
`composer require --dev hautelook/alice-bundle`

`AppKernel.php` file:
```php
<?php

    // ...

    public function registerBundles()
    {
        $bundles = array(
            new Symfony\Bundle\FrameworkBundle\FrameworkBundle(),
            new Symfony\Bundle\SecurityBundle\SecurityBundle(),
            new Symfony\Bundle\TwigBundle\TwigBundle(),
            new Symfony\Bundle\MonologBundle\MonologBundle(),
            new Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle(),
            new Doctrine\Bundle\DoctrineBundle\DoctrineBundle(),
            new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle(),
            new Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle(),
            new AppBundle\AppBundle(),
        );
        if (in_array($this->getEnvironment(), array('dev', 'test'), true)) {
            $bundles[] = new Symfony\Bundle\DebugBundle\DebugBundle();
            $bundles[] = new Symfony\Bundle\WebProfilerBundle\WebProfilerBundle();
            $bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
            $bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
            $bundles[] = new Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle();
            $bundles[] = new Hautelook\AliceBundle\HautelookAliceBundle();
        }
        return $bundles;
    }
    
    // ...
```

`composer.json` file:

```json
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "doctrine/doctrine-migrations-bundle": "^1.1"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^2.7",
        "doctrine/doctrine-fixtures-bundle": "^2.3",
        "hautelook/alice-bundle": "^1.2",
        "doctrine/data-fixtures": "^1.1"
    }
```

**Comment by kacperix** [comment]
It's duplicate of #196 (didn't notice it before). Closing.

I've updated symphony to 3.0.3 version and it's working.

**Comment by theofidry** [comment]
Glad you could sort your issue, I should add a requirement in the `composer.json` to avoid people falling into that trap...

**Comment by kacperix** [comment]
What I've noticed that Symfony 3.0.0 with PHP 5.6 works.
